config/routes.rb
Rails.application.routes.draw do

  mount RedactorRails::Engine => '/redactor_rails'
  get 'aphorisms/rules' => 'aphorisms#rules', as: 'rules'
  get 'aphorisms/ratings' => 'aphorisms#rating', as: 'ratings'
  get 'aphorisms/first_step' => 'aphorisms#step_one', as: 'step_one'
  get 'aphorisms/second_step' => 'aphorisms#step_two', as: 'step_two'
  get 'aphorisms/third_step/:picture_id' => 'aphorisms#step_three', as: 'step_three'
  get 'aphorisms/vk_answer' => 'aphorisms#vk_answer', as: 'vk_answer'
  post 'make_aphorism' => 'aphorisms#make_aphorism', as: 'make_aphorism'
  post 'update_aphorism' => 'aphorisms#update_aphorism', as: 'update_aphorism'

  root 'aphorisms#home'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/background.rb
class Background < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  require 'RMagick'
  include Magick

  scope :best, -> { where.not(author: nil).order('rating DESC NULLS LAST') }

  def self.make_with_text(text, bkgnd, color = '#fff', pos = 'center')
    align = {
              'left'   => NorthWestGravity,
              'right'  => NorthEastGravity,
              'center' => NorthGravity
            }
    pic = Picture.new
    img =  ImageList.new('public'+bkgnd.image_url(:big))
    txt = Draw.new
    # 18 is length of strings in the image text
    str = text.gsub(/(.{1,#{18}})(\s+|$)/, "\\1\n").strip.first(270)
    # 240 width of the text rectangle
    # 290 height of the text rectangle
    img.annotate(txt, 240,290,13,50, str){
      txt.pointsize = 26
      txt.font_family = 'Liberation Sans'
      #txt.stroke = '#000000'
      txt.font_weight = 700
      txt.fill = color
      txt.gravity = NorthGravity # align[pos]
    }

    img.write('test.jpg')
    pic.description = text
    pic.image = File.open('test.jpg')
    pic.save! ? pic : nil
  end
end

app/models/redactor_rails/asset.rb
class RedactorRails::Asset < ActiveRecord::Base
  include RedactorRails::Orm::ActiveRecord::AssetBase
  delegate :url, :current_path, :size, :content_type, :filename, :to => :data
  validates_presence_of :data
end

app/models/redactor_rails/document.rb
class RedactorRails::Document < RedactorRails::Asset
  mount_uploader :data, RedactorRailsDocumentUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end

  def as_json_methods
    [:image]
  end
end

app/models/redactor_rails/picture.rb
class RedactorRails::Picture < RedactorRails::Asset
  mount_uploader :data, RedactorRailsPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/text.rb
class Text < ActiveRecord::Base
end

app/controllers/aphorisms_controller.rb
class AphorismsController < ApplicationController

  layout 'main_page', only: [:home]

  def home;  end

  def rules
    @aphorisms = Picture.best.last(5)
  end

  def step_one
    @backgrounds = Background.all
  end

  def step_two
    @aphorisms = Picture.best.first(5)
    @background = Background.find(params[:background].to_i)
  end

  def make_aphorism
    txt = params[:description]
    bkg = Background.find(params[:image].to_i)
    if (p = Picture.make_with_text(txt, bkg, params[:color], params[:align]))
      render json: { url: step_three_path(p.id) }
    end
  end

  def update_aphorism
    pic = Picture.find params[:id]
    if pic.update(
          author: params[:author],
          username: params[:username],
          post_id: params[:post_id]
        )
      render json: {status: :ok}
    end
  end

  def step_three
    @aphorisms = Picture.best.first(5)
    @picture = Picture.find(params[:picture_id])
  end

  def vk_answer
    file = "public/uploads/picture/image/#{params[:photo].split('/')[-2]}/#{params[:photo].split('/').last}"
    app = VK::Application.new(app_id: 4617493)
    x = app.upload( url: params[:upload_url], file1: [file, 'image/jpeg'] )
    render json: x.body
  end

  def rating
    @page = (params[:page] || 1).to_i
    @aphorisms = Picture.best.page(@page).per 5
  end

  def permitted_params
    params.permit [:image, :description, :author, :username, :post_id]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :load_texts

  private
  def load_texts
    @text ||= Text.last
  end

end

app/helpers/aphorism_helper.rb
module AphorismHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/texts/_form.html.haml
= semantic_form_for [:admin, @text]  do |f|
  = f.semantic_errors *f.object.errors.keys
  =f.inputs 'Title' do
    = f.input :title, label: false
  =f.inputs 'Main page text' do
    = f.input :home, input_html: {class: :redactor}, label: false
  =f.inputs 'Rules page text' do
    = f.input :rules, input_html: {class: :redactor}, label: false
  =f.inputs 'Ratings page text' do
    = f.input :rating, input_html: {class: :redactor}, label: false
  =f.inputs 'Step1 page text' do
    = f.input :step1, input_html: {class: :redactor}, label: false
  =f.inputs 'Step2 page text' do
    = f.input :step2, input_html: {class: :redactor}, label: false
  =f.inputs 'Step3 page text' do
    = f.input :step3, input_html: {class: :redactor}, label: false
  =f.inputs 'Authorize page text' do
    = f.input :authorize, input_html: {class: :redactor}, label: false

  = f.actions

app/views/aphorism/_navigation.html.haml
.navigation
  .navigation_content
    .first_step.active_step
      .step_number
        01
      .step_title
        ВЫБЕРИТЕ ФОН
      .step_narrow
        >
    .second_step
      .step_number
        02
      .step_title
        ДОБАВТЕ АФОРИЗМ
      .step_narrow
        >
    .third_step
      .step_number
        03
      .step_title
        ОПУБЛИКУЙТЕ АФОРИЗМ

app/views/aphorism/step_one.html.haml
= render 'navigation'
.main_content
  .step_content
    .step_content__background
      = image_tag @backgrounds.first.image_url(:big),{class: 'js_big_background'}
    .step_content__body
      .step_content__body__title
        Выберите дизайн фона
      .step_content__body__text
        Текст-подсказка: lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      .step_content__body__actions
        = link_to 'ДОБАВИТЬ АФОРИЗМ >', '#', {class: 'red_button_link'}
  .clearfix
  .backgrounds_list
    - @backgrounds.each_with_index do |background, i|
      - klass = (i == 0 ? 'selected_background' : '')
      .background_image.js_background{data: { img: background.image_url(:big) }, class: klass}
        = image_tag background.image_url(:thumb)

app/views/aphorisms/_navigation.html.haml
.navigation
  .navigation_content
    .first_step{class: ('active_step' if params[:action] == 'step_one')}
      .step_number
        01
      .step_title
        ВЫБЕРИТЕ ФОН
      .step_narrow
        >
    .second_step{class: ('active_step' if params[:action] == 'step_two')}
      .step_number
        02
      .step_title
        ДОБАВЬТЕ АФОРИЗМ
      .step_narrow
        >
    .third_step{class: ('active_step' if (params[:action] == 'step_three' && @picture && @picture.author.blank?))}
      .step_number
        03
      .step_title
        ОПУБЛИКУЙТЕ АФОРИЗМ

app/views/aphorisms/home.html.haml
.main_page__container
  .main_content
    .logo

    .main_content__text
      .main_content__text__title
        .big_title Конкурс афоризмов
        .med_title от клиники высшей категории "ГрандМед"

      .main_content__text__body
        -if @text
          = @text.home.html_safe
        - else
          Сервис представляет собой генератор афоризм-картинок. Афоризм-картинка состоит из подложки и текста афоризма. Пользователь может поделиться картинкой в соц. сети Вконтакте
          и тем самым принять участие в конкурсе.

    .main_content__text__button
      = link_to 'УЧАСТВОВАТЬ В КОНКУРСЕ >', step_one_path, {class: 'white_button_link'}

    .main_content__text__links
      = link_to 'Правила конкурса', rules_path
      = link_to 'Рейтинг участников', ratings_path

    - if Picture.any?
      .main_content__text__aphorisms
        .main_content__text__aphorisms__title
          Лучшие афоризмы:
        .main_content__text__aphorisms__top
          - Picture.best.first(3).each do |pic|
            = image_tag pic.image_url(:thumb)

app/views/aphorisms/rating.html.haml
- content_for :js_src do
  %script{:src => "//vk.com/js/api/openapi.js", :type => "text/javascript"}
.navigation
  .navigation_content
    .navigation_content__page_title
      Рейтинг участников
    .navigation_content__button
      = link_to 'УЧАСТВОВАТЬ В КОНКУРСЕ >', step_one_path, {class: 'white_button_link'}
.main_content
  .main_content__rules_text.main_content__rating
    .rating_item.header_rating_item
      .rating_item__name
        Участники
      .rating_item__aphorism
        Афоризмы
      .rating_item__rate
        Рейтинг
      .clearfix

    - @aphorisms.each_with_index do |aphorism, i|
      - index = (i+1)+((@page-1)*5)
      - top = index < 4
      .rating_item
        .rating_item__name{ class: ('rating_top' if top) }
          = "#{index}. #{aphorism.username}"
          - if top
            = image_tag('karona.jpg')
        .rating_item__aphorism
          %a{ href: step_three_path(aphorism.id) }
            = image_tag aphorism.image_url(:thumb)
        .rating_item__rate
          = aphorism.rating.to_i
        .clearfix
    %br
    %br
    %br
    -if @text
      = @text.rating.html_safe

  .main_content__vk_widget#vk_groups

  .clearfix

  .rating_pagination
    = paginate @aphorisms

:javascript
  VK.Widgets.Group("vk_groups", {mode: 0, width: "300", height: "250"}, 32373473);

app/views/aphorisms/rules.html.haml
- content_for :js_src do
  %script{:src => "//vk.com/js/api/openapi.js", :type => "text/javascript"}
.navigation
  .navigation_content
    .navigation_content__page_title
      Правила конкурса
    .navigation_content__button
      = link_to 'УЧАСТВОВАТЬ В КОНКУРСЕ >', step_one_path, {class: 'white_button_link'}
.main_content
  .main_content__rules_text
    -if @text
      = @text.rules.html_safe
    - else
      Сервис представляет собой генератор афоризм-картинок. Три несложных шага для участия в конкурсе на лучший афоризм: выбрать подложку, написать афоризм, опубликовать картинку с афоризмом на своей стене в VK - и Вы сможете стать участником конкурса и получить приз от Клиники «ГрандМед». Обращаем Ваше внимание, что в конкурсе могут принимать участие только участники группы grandmed в VK.
      %br
      %br
      Итоги подводятся три раза в год:
      %br
      = '-  конец июнь'
      %br
      = '-  конец сентябрь'
      %br
      = '-  конец декабрь'
      %br
      Победители определяются по количеству лайков и комментарием «по существу» под Гранд-Афоризмом.
      %br
      %br
      Призы: сертификаты на услуги Клиники «ГрандМед» на 15 000, 10 000 и 5 000 рублей
  .main_content__vk_widget#vk_groups

  .clearfix
  .aphorisms_title
    Лучшие афоризмы
  .backgrounds_list
    - @aphorisms.each do |background|
      .background_image{data: { img: background.image_url(:thumb) }}
        = image_tag background.image_url(:thumb)

:javascript
  VK.Widgets.Group("vk_groups", {mode: 0, width: "300", height: "250"}, 32373473);

app/views/aphorisms/step_one.html.haml
= render 'navigation'
.main_content
  .step_content
    .step_content__background
      = image_tag @backgrounds.first.image_url(:big),{class: 'js_big_background'}
    .step_content__body
      .step_content__body__title
        Выберите дизайн фона
      .step_content__body__text
        -if @text
          = @text.step1.html_safe
        - else
          Выберите дизайн фона для Вашего Гранд-Афоризма из предложенных ниже иллюстраций.
      .step_content__body__actions
        = link_to 'ДОБАВИТЬ АФОРИЗМ >', step_two_path(background: @backgrounds.first.id), {class: 'red_button_link js_next_step_link'}
  .clearfix
  .backgrounds_list
    - @backgrounds.each_with_index do |background, i|
      - klass = (i == 0 ? 'selected_background' : '')
      .background_image.js_background{data: { img: background.image_url(:big), id: background.id }, class: klass}
        = image_tag background.image_url(:thumb)

app/views/aphorisms/step_three.html.haml
- content_for :js_src do
  %script{:src => "//vk.com/js/api/openapi.js", :type => "text/javascript"}

:javascript
  VK.init({apiId: 4617493});

= render 'navigation'
.main_content
  .step_content
    .step_content__background.background_for_text
      = image_tag @picture.image_url(:big),{class: 'js_big_background'}
      .step_content__background__text.js_aphorism_text
    .step_content__body
      - if @picture.author
        .step_content__body__title
          Конкурс афоризмов
        .step_content__body__text
          Автор:
          = link_to @picture.username, "http://vk.com/id#{@picture.author}", {target: '_blank', rel: 'nofollow'}

      - else
        - if params[:uid].present?
          .step_content__body__title
            Опубликуйте афоризм
          .step_content__body__text
          -if @text
            = @text.step3.html_safe
          - else
            Текст-подсказка: lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
          .step_content__body__actions
            = link_to 'ОПУБЛИКОВАТЬ АФОРИЗМ >', '#', {class: 'red_button_link js_public_aphorism', data: {pic: params[:picture_id]}}
            = image_tag 'http://vk.com/images/share_32.png', { width: '57', height: '57'}

        - else
          .step_content__body__title
            Авторизуйтесь через ВКонтакте
          .step_content__body__text
            -if @text
              = @text.authorize.html_safe
            - else
              Пожалуйста, войдите через виджет Вконтакте. Авторизация необходима только для сбора статистики по опубликованному во ВКонтакте грандмед-афоризму.
          .step_content__body__actions

            #login_button{onclick: 'VK.Auth.login(authInfo, VK.access.PHOTOS);'}

  .clearfix
  .aphorisms_title
    Лучшие афоризмы
  .backgrounds_list
    - @aphorisms.each do |background|
      .background_image{data: { img: background.image_url(:thumb) }}
        %a{ href: step_three_path(background.id) }
          = image_tag background.image_url(:thumb)
- unless @picture.author
  :javascript

    VK.Auth.getLoginStatus(authInfo);
    if (window.location.search.substring('uid').length > 4){}
    else{
      VK.UI.button('login_button');
    }

    function authInfo(response) {
      if (response.session) {
        prepare_wall_post_vk(response);
      } else {
        console.log('not auth');
      }
    }

    $(document).on('click', '.js_public_aphorism', function(e){
      e.preventDefault();
      var name;
      if (typeof localStorage['vk_user_name'] != 'undefined'){
        name = localStorage['vk_user_name']
      }
      else{
        name = 'id' + localStorage['vk_user_id']
      }

      VK.api('wall.post', {
          owner_id: localStorage['vk_user_id'],
          from_group: 0,
          message: 'Создаю афоризмы вместе с ГрандМедом http://grandaforizm.ru',
          attachments: localStorage['vk_photo_upload']
        }, function(data) {
          if (data.response){
            $.ajax({
              type: 'POST',
              dataType: 'json',
              url: '/update_aphorism',
              data: {
                id: "#{params[:picture_id]}",
                username: name,
                author: localStorage['vk_user_id'],
                post_id: data.response.post_id
              }
            }).done(function(msg) {
              window.location = document.URL.split('?')[0];
            });
          }
        }
      );
    });

    function prepare_wall_post_vk(response){
      if (window.location.search.substring('uid').length > 4){}
      else{
        var text = document.URL.split('?')[0];
        var title = 'Конкурс афоризмов - GrandMed';
        var imglink = "#{image_url(@picture.image_url(:big))}";
        var user_id = response.session.mid;
        if (typeof response.user != 'undefined'){
          localStorage['vk_user_name'] = response.user.last_name + ' ' + response.user.last_name;
        }
        VK.api('photos.getWallUploadServer', {
          uid: user_id
        }, function (data) {
          if (data.response) {
            $.ajax({
              type: 'GET',
              dataType: 'json',
              url: '/aphorisms/vk_answer',
              data: {
                photo: imglink,
                upload_url: data.response.upload_url
              }
            }).done( function(json){
              VK.api("photos.saveWallPhoto", {
                  server: json.server,
                  photo: json.photo,
                  hash: json.hash,
                  uid: user_id
                }, function(data){
                  localStorage['vk_user_id'] = user_id;
                  localStorage['vk_photo_upload'] = data.response['0'].id;
                  if (typeof localStorage['vk_user_name'] == 'undefined'){
                    VK.Api.call('users.get', {uids: user_id, fields: 'first_name,last_name'}, function(r) {
                      if (r.response){
                        localStorage['vk_user_name'] = r.response[0].first_name + ' ' + r.response[0].last_name;
                      }
                    });
                  }
                  return window.location = window.location + '?uid='+ user_id;
                }
              );
            }).fail(function(data){
              alert('Ошибка');
            });
          }
        });
      }
    }

app/views/aphorisms/step_two.html.haml
- if Rails.env.development?
  = javascript_include_tag '/jscolor/jscolor'
- else
  = javascript_include_tag '/assets/jscolor/jscolor'
= render 'navigation'
.main_content
  .step_content
    .step_content__background.background_for_text
      = image_tag @background.image_url(:big),{class: 'js_big_background'}
      .step_content__background__text.js_aphorism_text
    .step_content__body
      .step_content__body__title
        Добавьте афоризм
      .step_content__body__input
        %textarea{ cols: 60, rows: 10, id: 'aphorism_input' }
        .notification.js_notification
          Вы можете ввести не более 270 символов. Осталось:
          %span.js_notification_count
            270
          символа(ов)
        %b
          = label_tag 'Выберите цвет'
        = text_field_tag :picture, :color, { class: 'color' }
        %br
        %b
          = label_tag 'Выравнивание текста:'
        %br
        .align_field
          = label_tag 'Слева'
          %input#text_left{name: 'text[align]', type: 'radio', value: 'left'}
        .align_field
          = label_tag 'По центру'
          %input#text_left{checked: 'checked', name: 'text[align]', type: 'radio', value: 'center'}
        .align_field
          = label_tag 'Справа'
          %input#text_left{name: 'text[align]', type: 'radio', value: 'right'}

      .step_content__body__text
        -if @text
          = @text.step2.html_safe
        - else
          Напишите Ваш афоризм.
      .step_content__body__actions
        = link_to 'ОПУБЛИКУЙТЕ АФОРИЗМ >', '#', {class: 'red_button_link js_make_aphorism', data: {bkg: params[:background]}}
  .clearfix
  .aphorisms_title
    Лучшие афоризмы
  .backgrounds_list
    - @aphorisms.each do |background|
      .background_image{data: { img: background.image_url(:thumb) }}
        %a{ href: step_three_path(background.id) }
          = image_tag background.image_url(:thumb)

:javascript
  $("input[type='radio']").on('click', function(e){
    var align = $(this).val();
    $('.js_aphorism_text').css('text-align', align);
  });
  $('#picture').on('change', function(e){
    clr = '#' + $('#picture').val();
    $('.js_aphorism_text').css('color', clr);
  });
  $('#aphorism_input').on('keydown', function(e) {
    if ($('#aphorism_input').val().length > 269){
      $('.js_notification').addClass('error_notification');
      e.preventDefault();
    }
  });
  $('#aphorism_input').on('keyup', function(e) {
    clr = '#' + $('#picture').val();
    if ($('#aphorism_input').val().length > 269){
      $('.js_notification').addClass('error_notification');
      e.preventDefault();
    }else{
      $('.error_notification').removeClass('error_notification');
    }

    $('.js_notification_count').text(270 - $('#aphorism_input').val().length);
    $('.js_aphorism_text').html($('#aphorism_input').val().replace(/(?:\r\n|\r|\n)/g, '<br />')).css('color', clr);
  });

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title GrandMed
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = yield :js_src
    -#%script{:src => 'http://vk.com/js/api/openapi.js', :type => 'text/javascript'}
    = csrf_meta_tags
  %body
    .header
      %a.logo{href: '/'}
        = image_tag(image_url('logo.jpg'))

      .header__pages_links
        %a.header__pages_links__rooles{href: rules_path} Правила конкурса
        %a.header__pages_links__rating{href: ratings_path} Рейтинг участников

    .main_container
      = yield

    / Yandex.Metrika counter
    :javascript
      (function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter31936831 = new Ya.Metrika({id:31936831, webvisor:true, clickmap:true, trackLinks:true, accurateTrackBounce:true}); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks");
    %noscript
      %div
        %img{:alt => "", :src => "//mc.yandex.ru/watch/31936831", :style => "position:absolute; left:-9999px;"}/
    / /Yandex.Metrika counter

app/views/layouts/main_page.html.haml
!!!
%html
  %head
    %title GrandMed
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield


    / Yandex.Metrika counter
    :javascript
      (function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter31936831 = new Ya.Metrika({id:31936831, webvisor:true, clickmap:true, trackLinks:true, accurateTrackBounce:true}); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks");
    %noscript
      %div
        %img{:alt => "", :src => "//mc.yandex.ru/watch/31936831", :style => "position:absolute; left:-9999px;"}/
  / /Yandex.Metrika counter